const seoulRegion = [
  {
    name: "강남구",
    style: "gangnam",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "gaepo", name: "개포동" },
      { value: "nonhyeon", name: "논현동" },
      { value: "daechi", name: "대치동" },
      { value: "dogok", name: "도곡동" },
      { value: "samseong", name: "삼성동" },
      { value: "segok", name: "세곡동" },
      { value: "suseo", name: "수서동" },
      { value: "sinsa", name: "신사동" },
      { value: "apgujeong", name: "압구정동" },
      { value: "yeoksam", name: "역삼동" },
      { value: "yulhyeon", name: "율현동" },
      { value: "irwon", name: "일원동" },
      { value: "jagok", name: "자곡동" },
      { value: "cheongdam", name: "청담동" },
    ],
  },
  {
    name: "강동구",
    style: "gangdong",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "gangil", name: "강일동" },
      { value: "godeok", name: "고덕동" },
      { value: "gil", name: "길동" },
      { value: "dunchon", name: "둔촌동" },
      { value: "myeongil", name: "명일동" },
      { value: "sangil", name: "상일동" },
      { value: "seongnae", name: "성내동" },
      { value: "amsa", name: "암사동" },
      { value: "cheonho", name: "천호동" },
    ],
  },
  {
    name: "강북구",
    style: "gangbuk",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "mia", name: "미아동" },
      { value: "bun", name: "번동" },
      { value: "samgaksan", name: "삼각산동" },
      { value: "samyang", name: "삼양동" },
      { value: "songjung", name: "송중동" },
      { value: "songcheon", name: "송천동" },
      { value: "suyu", name: "수유동" },
      { value: "ui", name: "우이동" },
      { value: "insu", name: "인수동" },
    ],
  },
  {
    name: "강서구",
    style: "gangseo",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "gayang", name: "가양동" },
      { value: "gaehwa", name: "개화동" },
      { value: "gonghang", name: "공항동" },
      { value: "gwahae", name: "과해동" },
      { value: "naebalsan", name: "내발산동" },
      { value: "deungchon", name: "등촌동" },
      { value: "magok", name: "마곡동" },
      { value: "banghwa", name: "방화동" },
      { value: "yeomchang", name: "염창동" },
      { value: "ogok", name: "오곡동" },
      { value: "osoe", name: "오쇠동" },
      { value: "oebalsan", name: "외발산동" },
      { value: "ujangsan", name: "우장산동" },
      { value: "hwagok", name: "화곡동" },
    ],
  },
  {
    name: "관악구",
    style: "gwanak",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "nakseongdae", name: "낙성대동" },
      { value: "nangok", name: "난곡동" },
      { value: "nanhyang", name: "난향동" },
      { value: "namhyeon", name: "남현동" },
      { value: "daehak", name: "대학동" },
      { value: "miseong", name: "미성동" },
      { value: "boramae", name: "보라매동" },
      { value: "bongcheon", name: "봉천동" },
      { value: "samseong", name: "삼성동" },
      { value: "seorim", name: "서림동" },
      { value: "seowon", name: "서원동" },
      { value: "seonghyeon", name: "성현동" },
      { value: "sillim", name: "신림동" },
      { value: "sinsa", name: "신사동" },
      { value: "shinwon", name: "신원동" },
      { value: "euncheon", name: "은천동" },
      { value: "inheon", name: "인헌동" },
      { value: "jowon", name: "조원동" },
      { value: "jungang", name: "중앙동" },
      { value: "cheongryong", name: "청룡동" },
      { value: "cheonglim", name: "청림동" },
      { value: "haengun", name: "행운동" },
    ],
  },
  {
    name: "광진구",
    style: "gawngjin",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "gwangjang", name: "광장동" },
      { value: "guui", name: "구의동" },
      { value: "gunja", name: "군자동" },
      { value: "neung", name: "능동" },
      { value: "jayang", name: "자양동" },
      { value: "junggok", name: "중곡동" },
      { value: "hwayang", name: "화양동" },
    ],
  },
  {
    name: "구로구",
    style: "guro",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "garibong", name: "가리봉동" },
      { value: "gaebong", name: "개봉동" },
      { value: "gocheok", name: "고척동" },
      { value: "guro", name: "구로동" },
      { value: "gung", name: "궁동" },
      { value: "sindorim", name: "신도림동" },
      { value: "oryu", name: "오류동" },
      { value: "Onsu", name: "온수동" },
      { value: "cheonwang", name: "천왕동" },
      { value: "hang", name: "항동" },
    ],
  },
  {
    name: "금천구",
    style: "geumcheon",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "gasan", name: "가산동" },
      { value: "doksan", name: "독산동" },
      { value: "siheung", name: "시흥동" },
    ],
  },
  {
    name: "노원구",
    style: "nowon",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "gongneung", name: "공릉동" },
      { value: "sanggye", name: "상계동" },
      { value: "wolgye", name: "월계동" },
      { value: "junggye", name: "중계동" },
      { value: "hagye", name: "하계동" },
    ],
  },
  {
    name: "도봉구",
    style: "dobong",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "dobong", name: "도봉동" },
      { value: "banghak", name: "방학동" },
      { value: "ssangmun", name: "쌍문동" },
      { value: "chang", name: "창동" },
    ],
  },
  {
    name: "동대문구",
    style: "dongdaemun",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "dapsimni", name: "답십리동" },
      { value: "Sinseol", name: "신설동" },
      { value: "yongdu", name: "용두동" },
      { value: "imun", name: "이문동" },
      { value: "jangan", name: "장안동" },
      { value: "jeonnong", name: "전농동" },
      { value: "jegi", name: "제기동" },
      { value: "cheongnyangni", name: "청량리동" },
      { value: "hoegi", name: "회기동" },
      { value: "hwigyeong", name: "휘경동" },
    ],
  },
  {
    name: "동작구",
    style: "dongjak",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "noryangjin", name: "노량진동" },
      { value: "daebang", name: "대방동" },
      { value: "dongjak", name: "동작동" },
      { value: "bon", name: "본동" },
      { value: "sadang", name: "사당동" },
      { value: "sangdo", name: "상도동" },
      { value: "sindaebang", name: "신대방동" },
      { value: "heukseok", name: "흑석동" },
    ],
  },
  {
    name: "마포구",
    style: "mapo",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "gongdeok", name: "공덕동" },
      { value: "gusu", name: "구수동" },
      { value: "nogosan", name: "노고산동" },
      { value: "dangin", name: "당인동" },
      { value: "daeheung", name: "대흥동" },
      { value: "dohwa", name: "도화동" },
      { value: "donggyo", name: "동교동" },
      { value: "mapo", name: "마포동" },
      { value: "mangwon", name: "망원동" },
      { value: "sangsu", name: "상수동" },
      { value: "sangam", name: "상암동" },
      { value: "seogyo", name: "서교동" },
      { value: "seongsan", name: "성산동" },
      { value: "singongdeok", name: "신공덕동" },
      { value: "sinsu", name: "신수동" },
      { value: "sinjeong", name: "신정동" },
      { value: "ahyeon", name: "아현동" },
      { value: "yeonnam", name: "연남동" },
      { value: "yeomri", name: "염리동" },
      { value: "yonggang", name: "용강동" },
      { value: "jung", name: "중동" },
      { value: "changjeon", name: "창전동" },
      { value: "tojeong", name: "토정동" },
      { value: "hajung", name: "하중동" },
      { value: "hapjeong", name: "합정동" },
      { value: "hyeonseok", name: "현석동" },
    ],
  },
  {
    name: "서대문구",
    style: "seodaemun",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "namgajwa", name: "남가좌동" },
      { value: "naengcheon", name: "냉천동" },
      { value: "daesin", name: "대신동" },
      { value: "daehyeon", name: "대현동" },
      { value: "meegeunk", name: "미근동" },
      { value: "bongwon", name: "봉원동" },
      { value: "bukgajwa", name: "북가좌동" },
      { value: "bugahyeon", name: "북아현동" },
      { value: "sinchon", name: "신촌동" },
      { value: "yeonhui", name: "연희동" },
      { value: "yeongcheon", name: "영천동" },
      { value: "okcheon", name: "옥천동" },
      { value: "changcheon", name: "창천동" },
      { value: "cheonyeon", name: "천연동" },
      { value: "chungjeongno2-ga", name: "충정로2가" },
      { value: "chungjeongno3-ga", name: "충정로3가" },
      { value: "chunghyeon", name: "충현동" },
      { value: "hap", name: "합동" },
      { value: "hyeonjeo", name: "현저동" },
      { value: "hongeun", name: "홍은동" },
      { value: "hongje", name: "홍제동" },
    ],
  },
  {
    name: "서초구",
    style: "seocho",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "naegok", name: "내곡동" },
      { value: "banpo", name: "반포동" },
      { value: "bangbae", name: "방배동" },
      { value: "seocho", name: "서초동" },
      { value: "shinwon", name: "신원동" },
      { value: "yangjae", name: "양재동" },
      { value: "yeomgok", name: "염곡동" },
      { value: "umyeon", name: "우면동" },
      { value: "wonji", name: "원지동" },
      { value: "jamwon", name: "잠원동" },
    ],
  },
  {
    name: "성동구",
    style: "seongdong",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "geumho", name: "금호동" },
      { value: "doseon", name: "도선동" },
      { value: "majang", name: "마장동" },
      { value: "sagun", name: "사근동" },
      { value: "sangwangsimni", name: "상왕십리동" },
      { value: "seongsu", name: "성수동" },
      { value: "songjeong", name: "송정동" },
      { value: "oksu", name: "옥수동" },
      { value: "yongdap", name: "용답동" },
      { value: "eungbong", name: "응봉동" },
      { value: "hawangsimni", name: "하왕십리동" },
      { value: "haengdang", name: "행당동" },
      { value: "hongik", name: "홍익동" },
    ],
  },
  {
    name: "성북구",
    style: "seongbuk",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "gileum", name: "길음동" },
      { value: "donam", name: "돈암동" },
      { value: "dongseon", name: "동선동" },
      { value: "dongsomun", name: "동소문동" },
      { value: "bomun", name: "보문동" },
      { value: "samseon", name: "삼선동" },
      { value: "sangwolgok", name: "상월곡동" },
      { value: "seokgwan", name: "석관동" },
      { value: "seongbuk", name: "성북동" },
      { value: "anam", name: "안암동" },
      { value: "wolgok", name: "월곡동" },
      { value: "jangwi", name: "장위동" },
      { value: "jeongneung", name: "정릉동" },
      { value: "jongam", name: "종암동" },
      { value: "howolgok", name: "하월곡동" },
    ],
  },
  {
    name: "송파구",
    style: "songfa",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "garak", name: "가락동" },
      { value: "geoyeo", name: "거여동" },
      { value: "macheon", name: "마천동" },
      { value: "munjeong", name: "문정동" },
      { value: "bangi", name: "방이동" },
      { value: "samjeon", name: "삼전동" },
      { value: "seokchon", name: "석촌동" },
      { value: "songpa", name: "송파동" },
      { value: "sincheon", name: "신천동" },
      { value: "ogeum", name: "오금동" },
      { value: "oryun", name: "오륜동" },
      { value: "wirye", name: "위례동" },
      { value: "jamsil", name: "잠실동" },
      { value: "jangji", name: "장지동" },
      { value: "pungnap", name: "풍납동" },
    ],
  },
  {
    name: "양천구",
    style: "yangcheon",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "mok", name: "목동" },
      { value: "sinwol", name: "신월동" },
      { value: "sinjeong", name: "신정동" },
    ],
  },
  {
    name: "영등포구",
    style: "yeongdeungpo",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "dangsan", name: "당산동" },
      { value: "daelim", name: "대림동" },
      { value: "dorim", name: "도림동" },
      { value: "munrae", name: "문래동" },
      { value: "singil", name: "신길동" },
      { value: "yangpyeong", name: "양평동" },
      { value: "yanghwa", name: "양화동" },
      { value: "yeouido", name: "여의도동" },
      { value: "yeongdeungpo", name: "영등포동" },
    ],
  },
  {
    name: "용산구",
    style: "youngsan",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "galwol", name: "갈월동" },
      { value: "namyeong", name: "남영동" },
      { value: "dowon", name: "도원동" },
      { value: "dongbingo", name: "동빙고동" },
      { value: "dongja", name: "동자동" },
      { value: "munbae", name: "문배동" },
      { value: "bogwang", name: "보광동" },
      { value: "sancheon", name: "산천동" },
      { value: "seogye", name: "서계동" },
      { value: "seobinggo", name: "서빙고동" },
    ],
  },
  {
    name: "은평구",
    style: "eunpyeong",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "galhyeon", name: "갈현동" },
      { value: "gusan", name: "구산동" },
      { value: "nokbyeon", name: "녹번동" },
      { value: "daejo", name: "대조동" },
      { value: "bulgwang", name: "불광동" },
      { value: "susaek", name: "수색동" },
      { value: "sinsa", name: "신사동" },
      { value: "yeokchon", name: "역촌동" },
      { value: "eungam", name: "응암동" },
      { value: "jeungsan", name: "증산동" },
      { value: "jingwan", name: "진관동" },
    ],
  },
  {
    name: "종로구",
    style: "jungro",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "gahoe", name: "가회동" },
      { value: "gwansu", name: "관수동" },
      { value: "gwancheol", name: "관철동" },
      { value: "gyobuk", name: "교북동" },
      { value: "naesu", name: "내수동" },
      { value: "donui", name: "돈의동" },
      { value: "buam", name: "부암동" },
      { value: "samcheong", name: "삼청동" },
      { value: "sungin", name: "숭인동" },
      { value: "hyoje", name: "효제동" },
    ],
  },
  {
    name: "중구",
    style: "jung",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "gwanghui", name: "광희동" },
      { value: "namsan", name: "남산동" },
      { value: "namchang", name: "남창동" },
      { value: "dasan", name: "다산동" },
      { value: "myeong", name: "명동" },
      { value: "bongrae", name: "봉래동" },
      { value: "sindang", name: "신당동" },
      { value: "jangchung", name: "장충동" },
      { value: "hoehyeon", name: "회현동" },
      { value: "heungin", name: "흥인동" },
    ],
  },
  {
    name: "중랑구",
    style: "jungrang",
    Dong: [
      { value: "Init", name: "-----------" },
      { value: "mangu", name: "망우동" },
      { value: "myeonmok", name: "면목동" },
      { value: "muk", name: "묵동" },
      { value: "sangbong", name: "상봉동" },
      { value: "sinnae", name: "신내동" },
      { value: "junghwa", name: "중화동" },
    ],
  },
];

export { seoulRegion };
